version: "3.9" 
services:
  postgresql:
    image: istrebitel/ufoffice-postgres:latest
    ports:
      - 15432:5432
    restart: always
  python:
    image: istrebitel/ufoffice-api:latest
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgresql:5432/ufoffice
      BACKEND_HOST: python
      BACKEND_PORT: 5000
    ports:
      - 5000:5000
    depends_on:
      - postgresql
